In [6]:
 # version 3 print function
from __future__ import print_function 
# seed the pseudorandom number generator
from random import random, shuffle, seed
# seed random number generator
seed(1)

#import math and numpy packages
import math
import numpy as np

%matplotlib inline
# importing the required module 
import matplotlib.pyplot as plt 
plt.rcParams['figure.figsize'] = [10, 8] # for square canvas


#import copy
from copy import copy, deepcopy

In [7]:
#assembling heat pipe performance data array
#==========================================
#store array where rows are data vectors
#[Ta,in(deg C), Ta,out(deg C), qdot(W)]

ydata = [[ 27.2, 15.9, 31.2]]
ydata.append([ 29.6, 17.1, 37.0])
ydata.append([ 29.5, 18.1, 34.2])
ydata.append([ 30.4, 19.0, 31.])
ydata.append([ 30.4, 20.0, 28.5])
ydata.append([ 30.2, 21.0, 25.7])
ydata.append([ 30.0, 22.1, 22.8])
ydata.append([ 29.8, 22.9, 20.0])
ydata.append([ 29.9, 24.1, 17.1])
ydata.append([ 29.6, 24.9, 14.3])
ydata.append([ 29.5, 26.1, 11.4])
ydata.append([ 30.3, 26.9, 8.6])
ydata.append([ 32.5, 16.9, 45.7])
ydata.append([ 32.6, 18.1, 42.8])
ydata.append([ 32.6, 19.1, 40.0])
ydata.append([ 32.7, 20.2, 37.2])
ydata.append([ 32.9, 21.1, 34.3])
ydata.append([ 33.0, 22.0, 31.5])
ydata.append([ 32.5, 23.1, 28.7])
ydata.append([ 32.8, 24.1, 25.8])
ydata.append([ 33.0, 24.9, 23.0])
ydata.append([ 32.9, 26.0, 20.1])
ydata.append([ 33.1, 27.0, 17.2])
ydata.append([ 35.7, 17.0, 54.4])
ydata.append([ 35.6, 18.1, 51.6])
ydata.append([ 36.2, 19.1, 48.7])
ydata.append([ 36.3, 20.2, 45.9])
ydata.append([ 36.4, 21.1, 43.1])
ydata.append([ 35.5, 22.2, 40.2])
ydata.append([ 36.2, 22.9, 37.4])
ydata.append([ 36.2, 24.1, 34.5])
ydata.append([ 35.7, 25.0, 31.7])
ydata.append([ 36.0, 26.1, 28.8])
ydata.append([ 35.8, 27.1, 25.9])
ydata.append([ 38.8, 16.9, 63.1])
ydata.append([ 39.4, 18.1, 60.3])
ydata.append([ 38.9, 19.2, 57.5])
ydata.append([ 39.2, 20.1, 54.7])
ydata.append([ 38.5, 21.2, 51.8])
ydata.append([ 39.0, 22.0, 49.0])
ydata.append([ 39.0, 23.1, 46.1])
ydata.append([ 39.3, 24.0, 43.3])
ydata.append([ 39.3, 24.9, 40.4])
ydata.append([ 39.1, 26.2, 37.6])
ydata.append([ 39.1, 27.2, 34.7])
ydata.append([ 42.2, 17.0, 71.9])
ydata.append([ 42.3, 18.1, 69.1])
ydata.append([ 42.4, 18.9, 66.3])
ydata.append([ 41.9, 20.0, 63.5])
ydata.append([ 41.8, 21.0, 60.6])
ydata.append([ 41.8, 22.1, 57.8])
ydata.append([ 42.2, 22.8, 54.9])
ydata.append([ 41.5, 24.2, 52.1])
ydata.append([ 42.3, 25.3, 49.2])
ydata.append([ 41.8, 25.9, 46.3])
ydata.append([ 42.3, 26.8, 43.5])
ydata.append([ 45.2, 17.1, 80.8])
ydata.append([ 44.5, 18.2, 78.0])
ydata.append([ 44.8, 18.8, 75.1])
ydata.append([ 45.2, 20.0, 72.3])
ydata.append([ 44.9, 21.2, 69.5])
ydata.append([ 45.3, 22.1, 66.6])
ydata.append([ 44.5, 22.8, 63.8])
ydata.append([ 44.9, 24.1, 60.9])
ydata.append([ 44.8, 25.2, 58.1])
ydata.append([ 45.3, 26.2, 55.2])
ydata.append([ 44.9, 26.9, 52.3])
ydata.append([ 48.0, 17.2, 89.7])
ydata.append([ 47.7, 18.1, 86.9])
ydata.append([ 48.2, 18.9, 84.0])
ydata.append([ 48.3, 19.9, 81.2])
ydata.append([ 48.0, 20.0, 78.3])
ydata.append([ 48.4, 22.8, 75.5])
ydata.append([ 48.2, 23.0, 72.7])
ydata.append([ 47.6, 24.0, 69.8])
ydata.append([ 48.2, 25.1, 66.9])
ydata.append([ 48.2, 25.8, 64.1])
ydata.append([ 47.8, 26.9, 61.2])
ydata.append([ 50.5, 17.0, 98.6])
ydata.append([ 50.6, 18.0, 95.8])
ydata.append([ 50.5, 19.1, 93.0])
ydata.append([ 50.9, 20.1, 90.1])
ydata.append([ 51.0, 20.8, 87.3])
ydata.append([ 51.0, 21.9, 84.4])
ydata.append([ 50.5, 23.0, 81.6])
ydata.append([ 51.2, 24.1, 78.7])
ydata.append([ 50.8, 25.2, 75.9])
ydata.append([ 51.2, 25.9, 73.0])
ydata.append([ 51.0, 26.9, 70.1])
ydata.append([ 54.2, 17.1, 107.6])
ydata.append([ 53.5, 18.1, 104.8])
ydata.append([ 54.1, 19.1, 101.9])
ydata.append([ 53.5, 20.1, 99.1])
ydata.append([ 53.5, 21.2, 96.3])
ydata.append([ 54.2, 21.9, 93.4])
ydata.append([ 54.1, 23.2, 90.6])
ydata.append([ 53.8, 24.1, 87.7])
ydata.append([ 53.6, 25.0, 84.8])
ydata.append([ 53.9, 26.0, 82.0])
ydata.append([ 53.7, 26.8, 79.1])
ydata.append([ 57.2, 17.0, 116.7])
ydata.append([ 56.9, 18.1, 113.8])
ydata.append([ 57.0, 19.1, 111.0])
ydata.append([ 56.7, 19.8, 108.1])
ydata.append([ 57.3, 20.9, 105.3])
ydata.append([ 56.8, 21.9, 102.4])
ydata.append([ 57.4, 23.2, 99.6])
ydata.append([ 57.3, 23.8, 96.7])
ydata.append([ 56.6, 25.2, 93.8])
ydata.append([ 57.0, 25.8, 91.0])
ydata.append([ 57.2, 27.0, 88.1])
ydata.append([ 60.2, 16.9, 125.7])
ydata.append([ 59.9, 17.9, 122.9])
ydata.append([ 59.6, 19.1, 120.0])
ydata.append([ 60.2, 20.1, 117.2])
ydata.append([ 60.2, 20.9, 114.3])
ydata.append([ 60.4, 21.8, 111.5])
ydata.append([ 59.1, 22.9, 108.6])
ydata.append([ 59.1, 24.1, 105.8])
ydata.append([ 60.1, 25.2, 102.9])
ydata.append([ 59.1, 25.8, 100.0])
ydata.append([ 60.3, 26.9, 97.1])

yarray= np.array(ydata)
print (yarray)


[[ 27.2  15.9  31.2]
 [ 29.6  17.1  37. ]
 [ 29.5  18.1  34.2]
 [ 30.4  19.   31. ]
 [ 30.4  20.   28.5]
 [ 30.2  21.   25.7]
 [ 30.   22.1  22.8]
 [ 29.8  22.9  20. ]
 [ 29.9  24.1  17.1]
 [ 29.6  24.9  14.3]
 [ 29.5  26.1  11.4]
 [ 30.3  26.9   8.6]
 [ 32.5  16.9  45.7]
 [ 32.6  18.1  42.8]
 [ 32.6  19.1  40. ]
 [ 32.7  20.2  37.2]
 [ 32.9  21.1  34.3]
 [ 33.   22.   31.5]
 [ 32.5  23.1  28.7]
 [ 32.8  24.1  25.8]
 [ 33.   24.9  23. ]
 [ 32.9  26.   20.1]
 [ 33.1  27.   17.2]
 [ 35.7  17.   54.4]
 [ 35.6  18.1  51.6]
 [ 36.2  19.1  48.7]
 [ 36.3  20.2  45.9]
 [ 36.4  21.1  43.1]
 [ 35.5  22.2  40.2]
 [ 36.2  22.9  37.4]
 [ 36.2  24.1  34.5]
 [ 35.7  25.   31.7]
 [ 36.   26.1  28.8]
 [ 35.8  27.1  25.9]
 [ 38.8  16.9  63.1]
 [ 39.4  18.1  60.3]
 [ 38.9  19.2  57.5]
 [ 39.2  20.1  54.7]
 [ 38.5  21.2  51.8]
 [ 39.   22.   49. ]
 [ 39.   23.1  46.1]
 [ 39.3  24.   43.3]
 [ 39.3  24.9  40.4]
 [ 39.1  26.2  37.6]
 [ 39.1  27.2  34.7]
 [ 42.2  17.   71.9]
 [ 42.3  18.1  69.1]
 [ 42.4  18.9

In [19]:
shuffle(ydata)
training_percent = .8

training_count = int(len(ydata) * training_percent//1)

training_data = ydata[:training_count]
test_data = ydata[training_count:]

In [27]:


#Parameters for Evolution Loop
#set data parameters
ND = len(training_data)       #number of data vectors in array
DI = 5        #number of data items in vector
NS = ND       #total number of DNA strands


BOLTZMAN = 5.67 * 10**(-8)
HREF = 70


In [28]:
def predict(n1, n2, n3, t_in, t_out):
    hr = (t_in + t_out) * (t_in**2 + t_out**2) * BOLTZMAN
    return   n2 * (1+ n3 * (hr/HREF)) * \
            (n1 * (t_in - t_out) / n1 + n2*(1+ n3 * (hr/HREF)))

In [29]:
'''INITIALIZING PARAMETERS'''
n = []
ntemp = []
gen=[0]
n1avg = [0.0]
n2avg = [0.0]
n3avg = [0.0]
meanAFerr=[0.0]
aFerrmeanavgn=[0.0] 

#set program parameters
NGEN = 6000      #number of generations (steps)
MFRAC = 0.5   # faction of median threshold

# here the number of data vectors equals the number of DNA strands (or organisms)
# they can be different if they are randomly paired to compute Ferr (survivability) function
for k in range(NGEN-1):
    gen.append(k+1)   # generation array stores the
    meanAFerr.append(0.0)
    aFerrmeanavgn.append(0.0)
    n1avg.append(0.0)
    n2avg.append(0.0)
    n3avg.append(0.0)
    
'''guesses for initial solution population'''
n0i =  -1.0 
n1i = 0.00027
n2i = 4.0
n3i = 0.063


#- initialize arrays before start of evolution loop EL
#then - create array of DNA strands n[i] and ntemp[i] with dimesnion NS = 5

#i initialize array where rows are dna vectors [n0i,n1i,...n5i] with random pertubations
n =  [[-1., n1i+0.001*random(), n2i+0.1*random(), n3i+0.0001*random()]]
for i in range(ND):
    n.append([-1., n1i+0.0001*random(), n2i+0.001*random(), n3i+0.0001*random()])
#print (n) # uncomment command to print array so it can be checked

# store also in wtemp
ntemp = deepcopy(n)

#initialize Ferr values an dother loop parameters
#define arrays of Ferr (error) functions
#individual solution error and absoute error
Ferr =  [[0.0]]  
#population average solution error and absoute error
Ferravgn =  [[0.0]]
aFerr =  [[0.0]]
aFerravgn =  [[0.0]]

#store zeros in ND genes
for i in range(ND-1):
    #individual solution error and absoute error
    Ferr.append([0.0])
    aFerr.append([0.0])
    #population average solution error and absoute error
    Ferravgn.append([0.0])
    aFerravgn.append([0.0])
#print (Ferr)

aFerrmeanavgnMin=1000000000.0 
# these store the  n values for minimum population average error durng NGEN generations
n1min = 0.0
n2min = 0.0
n3min = 0.0
aFerrta = 0.0
# these store the time averaged n values durng from generation 800 to NGEN generations
n1min = 0.0
n1ta = 0.0
n2ta = 0.0
n3ta = 0.0


'''START OF EVOLUTION LOOP'''
# ------------------------------------------
# k is generation number, NGEN IS TOTAL NUMBER OF GENERATIONS COMPUTED
for k in range(NGEN):
    
    '''In this program , the number of organisms (solutions) NS is taken to be equal to the 
    number of data points ND so for each generation, each solution can be compared to a different 
    data point and all the data is compared in each generation.  The order of the solutions in the array 
    that holds the solution constants is constantly changing due to mating and selection, so the pairing 
    is random.'''
    
    
    '''CALCULATING ERROR (FITNESS)
    In this program, the absolute error in the logrithm of the physical heat flux is 
    used to evaluate fitness.'''
    
    # Here we calculate error Ferr and absolute error aFerr for each data point and organism pair 
    # for specified n(i), and calculate (mean aFerr) = aFerrmean
    # and (median aFerr) = aFerrmedian for the data collection and specified n(i)
    # Note that the number data points ND equals the number of solutions (organisms) in the population
    #====================================================================================
    '''CALCULATING ERROR (FITNESS)'''
    for i in range(ND):
        t_in, t_out, q_data = training_data[i]
        _, n1, n2, n3 = n[i]
        Ferr[i] =   q_data - predict(n1, n2, n3, t_in, t_out)
           
        aFerr[i] = abs(Ferr[i])/abs(q_data)  #- absolute fractional error
    #-------------
    aFerrmean = numpy.mean(aFerr) #mean error for population for this generation
    meanAFerr[k]=aFerrmean  #store aFerrmean for this generation gen[k]=k
    aFerrmedian = numpy.median(aFerr) #median error for population for this generation

    '''SELECTION'''
    #pick survivors 
    #[2] calculate survival cutoff, set number kept = nkeep = 0
    #==============================================
    clim = MFRAC*aFerrmedian  #cut off limit is a fraction/multiplier MFRAC of median value for population
    nkeep = 0
    
    # now check each organism/solution to see if aFerr is less than cut of limit
    #if yes, store n for next generation population in ntemp, at end nkeep = number that survive
    #and number of new offspring = NS-nkeep
    #==============================================
    for j in range(NS):  # NS Ferr values, one for each solution in population
        if (aFerr[j] < clim):
            nkeep = nkeep + 1
            #ntemp[nkeep][0] = n[j][0] = -1 so it is unchanged;
            ntemp[nkeep-1][1] = n[j][1];
            ntemp[nkeep-1][2] = n[j][2];
            ntemp[nkeep-1][3] = n[j][3];
    #now have survivors in leading entries in list of ntemp vectors from 1 to nkeep
    #compute number to be added by mating
    nnew = NS - nkeep  
    
    '''MATING'''
    #[4] for nnew new organisms/solutions,
    # randomly pick two survivors, randomly pick DNA (n) from pair for each offspring
    #==============================================================
    for j in range(nnew): 
        # pick two survivors randomly
        nmate1 = numpy.random.randint(low=0, high=nkeep+1)
        nmate2 = numpy.random.randint(low=0, high=nkeep+1)
        
        #then randomly pick DNA from parents for offspring
        
        '''here, do not change property ntemp[nkeep+j+1][0], it's always fixed at the value -1'''
        #if (numpy.random.rand() < 0.5)
        #    ntemp[nkeep+j+1][0] = n[nmate1][0]  
        #else
        #    ntemp[nkeep+j+1][0] = n[nmate2][0]
      
        if (numpy.random.rand() < 0.5):
            ntemp[nkeep+j+1][1] = n[nmate1][1]*(1.+0.09*2.*(0.5-numpy.random.rand()))  # property 1, mutation added
        else:
            ntemp[nkeep+j+1][1] = n[nmate2][1]*(1.+0.09*2.*(0.5-numpy.random.rand()))
    
        if (numpy.random.rand() < 0.5):
            ntemp[nkeep+j+1][2] = n[nmate1][2]*(1.+0.09*2.*(0.5-numpy.random.rand()))  # property 2, mutation added
        else:
            ntemp[nkeep+j+1][2] = n[nmate2][2]*(1.+0.09*2.*(0.5-numpy.random.rand()))
    
        if (numpy.random.rand() < 0.5):
            ntemp[nkeep+j+1][3] = n[nmate1][3]*(1.+0.09*2.*(0.5-numpy.random.rand()))  # property 3, mutation added
        else:
            ntemp[nkeep+j+1][3] = n[nmate2][3]*(1.+0.09*2.*(0.5-numpy.random.rand()))
            
    #=============================================
    n = deepcopy(ntemp)   # save ntemp as n for use in next generation (next iteration)
    
    
    '''AVERAGING OVER POPULATION AND OVER TIME, FINDING MINIMUM ERROR SET OF n VALUES'''
    # [6] calculate n1avg[k], etc., which are average n values for population of organisms (solutions) 
    # at this generation k
    #=============================================
    #initialize average n's to zero and sum contribution of each member of the solution population 
    n1avg[k] = 0.0;
    n2avg[k] = 0.0;
    n3avg[k] = 0.0;
    for j in range(NS):    
        n1avg[k] = n1avg[k] + n[j][1]/NS; 
        n2avg[k] = n2avg[k] + n[j][2]/NS; 
        n3avg[k] = n3avg[k] + n[j][3]/NS;

    # Here we compute aFerravgn[i] = absolute Ferr of logrithm data point i using average n values 
    # for this solutions generation k
    # aFerrmeanavgn[k] is the mean of the Ferravgn[i] for the population of organisms/solutions
    # 
    #=============================================
    ''' CALCULATING MEAN ERROR FOR POPULATION'''
    for i in range(ND): 
        t_in, t_out, q_data = training_data[i]
        Ferravgn[i] =   q_data - predict(n1avg[k], n2avg, n3avg, t_in, t_out)
            
        #aFerravgn[i] = abs(Ferr[i])/abs(lydata[i][0])
        aFerravgn[i] = abs(Ferravgn[i])/abs(q_data)
    #-------------
    aFerrmeanavgn[k] = numpy.mean(aFerravgn)
    
    
    # next, update time average of n valaues in population (n1ta[k], etc.) 
    # for generations = k > 800 up to total NGEN
    #=============================================
    aFerrta = aFerrta + aFerrmeanavgn[k]/NGEN
    if (k > 800):
        n1ta = n1ta + n1avg[k]/(NGEN-800)
        n2ta = n2ta + n2avg[k]/(NGEN-800)
        n3ta = n3ta + n3avg[k]/(NGEN-800)
    
    # compare aFerrmeanavgn[k] to previous minimum value and save 
    # it and corresponding n(i) values if the value for this generation k is lower 
    #=============================================
    if (aFerrmeanavgn[k] < aFerrmeanavgnMin):
        aFerrmeanavgnMin = aFerrmeanavgn[k] 
        n1min = n1avg[k]
        n2min = n2avg[k]
        n3min = n3avg[k]
    
    #print('avg n1-n4:', n1avg[k], n2avg[k], n3avg[k], n4avg[k], aFerrmeanavgn[k])
    #print ('kvalue =', k)
    '''end of evolution loop'''
    # ------------------------------------------------------------------
    # ------------------------------------------------------------------
    
    
# ------------------------------------------------------------------
#final print and plot of results
# ------------------------------------------------------------------
print('ENDING: pop. avg n1-n3,aFerrmean:', n1avg[k], n2avg[k], n3avg[k], aFerrmeanavgn[k])
print('MINUMUM:  avg n1-n3,aFerrmeanMin:', n1min, n2min, n3min, aFerrmeanavgnMin)
print('TIME AVG:    avg n1-n3,aFerrmean:', n1ta, n2ta, n3ta, aFerrta)

#SETTING UP PLOTS

#========
#initialize values
qpppred =  [[0.0]]
qppdata =  [[0.0]]
for i in range(ND-1):
    qpppred.append([0.0])
    qppdata.append([0.0])   
#calculate predicted and data values to plot
for i in range(ND):
    t_in, t_out, q_data = training_data[i]
    prediction = predict(n1min, n2min, n3min, t_in, t_out)
    qpppred[i] = prediction
    qppdata[i] = q_data

    
#========

# constants evolution plots
# x axis values are generation number 
# corresponding y axis values are mean absolute population error aFerrmeanavgn and n values
# plotting the points  

plt.rcParams.update({'font.size': 18})

# aFerrmeanavgn[k] is the mean of the Ferravgn[i] for the population of organisms/solutions
# computed using the mean n values
plt.plot(gen, aFerrmeanavgn) 
plt.plot(gen, n1avg)
plt.plot(gen, n2avg)
plt.plot(gen, n3avg)
plt.legend(['aFerrmeanavgn', 'n1 avg', 'n2 avg', 'n3 avg'], loc='lower left')

# naming the x axis 
plt.xlabel('generation') 
# naming the y axis 
plt.ylabel('constants and error') 
plt.loglog()
plt.yticks([0.01,0.1,1.0,10])
plt.xticks([1,10,100,1000,10000]) 
plt.show() 


'''CALCULATE PREDICTED VALUES AND RETRIEVE DATA VALUES TO PLOT'''
plt.scatter(qpppred, qppdata)
plt.title('Genetic Algorithm')
plt.xlabel('predicted heat flux (W/cm^2), n1min - n3min constants')
plt.ylabel('measured heat flux (W/cm^2)')
plt.loglog()
plt.xlim(xmax = 1000, xmin = 10)
plt.ylim(ymax = 1000, ymin = 10)

plt.show()
    
# end CodeP1.2F24 

TypeError: can't multiply sequence by non-int of type 'float'

In [42]:
sq_err_total = 0
err_prcts = []
for pred_point, data_point in zip(qpppred, qppdata):
    err_prcts.append(math.sqrt((pred_point - data_point)**2) / data_point)
    sq_err_total += (pred_point - data_point)**2

res = sq_err_total/len(qpppred)
rms = math.sqrt(res)

diff = max_data - min_data

print(f"RMS: {rms}")
print(f"RMS percent: {sum(err_prcts)/len(err_prcts)}")

RMS: 25.90579450419242
RMS percent: 0.13873528904216217
